Found error when trying to Train
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
Make it has something to do with the value being too large because I fix all the NaN and infinity.